/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a subscription
         * @description Returns full details of a subscription owned by the authenticated user.
         */
        get: operations["findById"];
        /**
         * Update a subscription
         * @description Replaces a subscription's name, search filter, and delivery settings. Does not change whether the subscription is active — use pause/resume for that.
         */
        put: operations["update"];
        post?: never;
        /**
         * Delete a subscription
         * @description Permanently deletes a subscription.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my subscriptions
         * @description Returns a paginated list of subscriptions owned by the authenticated user.
         */
        get: operations["findMine"];
        put?: never;
        /**
         * Create a subscription
         * @description Creates a new active subscription from a search filter. Fails with 422 if the user's tariff active subscription limit is reached.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange Telegram WebApp initData for a JWT
         * @description Validates the signature and freshness of Telegram WebApp initData, creates the user on first login, and issues a JWT access token.
         */
        post: operations["telegramLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Resume a subscription
         * @description Reactivates a paused subscription. Fails with 422 if the user's tariff active subscription limit is reached.
         */
        patch: operations["resume"];
        trace?: never;
    };
    "/api/v1/subscriptions/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Pause a subscription
         * @description Stops notifications for the subscription until resumed.
         */
        patch: operations["pause"];
        trace?: never;
    };
    "/api/v1/admin/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a source
         * @description Enables/disables a source and/or changes its configured sync interval. Disabled sources are skipped by all scheduled sync jobs.
         */
        patch: operations["updateSource"];
        trace?: never;
    };
    "/api/v1/admin/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update listing status
         * @description Manually changes a listing's status, e.g. to deactivate a listing the source connector has not yet retired.
         */
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/api/v1/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search listings
         * @description Returns a paginated list of listings matching the filter criteria. Defaults to ACTIVE listings when status is not specified.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get listing by ID
         * @description Returns full details of a single listing including its price change history.
         */
        get: operations["findById_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sync-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sync runs
         * @description Returns a paginated history of connector sync runs, newest first. Filter by sourceId to see runs for a single source.
         */
        get: operations["findSyncRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sync-runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get latest sync run per source
         * @description Returns the most recent sync run — successful or failed — for each registered source.
         */
        get: operations["findLatestSyncRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sources
         * @description Returns every registered data source with its status, sync interval, and last successful sync time.
         */
        get: operations["findSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search listings for moderation
         * @description Returns a paginated list of listings matching the filter criteria, across all statuses unless status is specified. Set duplicatesOnly=true to see listings that share a deduplication hash with another listing.
         */
        get: operations["search_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/listings/{id}/duplicate-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unlink a listing from its duplicate group
         * @description Clears the listing's deduplication hash so it is no longer grouped with listings the deduplication process considered the same property. Other listings in the group are left unchanged.
         */
        delete: operations["unlinkDuplicateGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error response body */
        ErrorResponse: {
            /**
             * Format: date-time
             * @description Time when the error occurred
             * @example 2026-01-15T11:00:00Z
             */
            timestamp?: string;
            /**
             * Format: int32
             * @description HTTP status code
             * @example 404
             */
            status?: number;
            /**
             * @description Short error classification
             * @example Not Found
             */
            error?: string;
            /**
             * @description Human-readable error message
             * @example Listing not found: 42
             */
            message?: string;
            /**
             * @description Request path that produced the error
             * @example /api/v1/listings/42
             */
            path?: string;
            /** @description Field-level validation errors; empty for non-validation errors */
            errors?: components["schemas"]["ValidationError"][];
        };
        /** @description A single field-level validation error */
        ValidationError: {
            /**
             * @description The field that failed validation
             * @example priceMin
             */
            field?: string;
            /**
             * @description Human-readable validation message
             * @example must be greater than or equal to 0
             */
            message?: string;
        };
        /**
         * @description End of the quiet hours window
         * @example 08:00:00
         */
        LocalTime: {
            /** Format: int32 */
            hour?: number;
            /** Format: int32 */
            minute?: number;
            /** Format: int32 */
            second?: number;
            /** Format: int32 */
            nano?: number;
        };
        /** @description Search filter that a subscription matches new and changed listings against */
        SubscriptionSearchCriteria: {
            /**
             * @description Deal type filter: RENT, SELL, or RENT_DAILY
             * @example RENT_DAILY
             * @enum {string}
             */
            dealType?: "RENT" | "SELL" | "RENT_DAILY";
            /**
             * @description Property type filter
             * @example APARTMENT
             */
            propertyType?: string;
            /**
             * @description Source platform code filter
             * @example onliner
             */
            sourceId?: string;
            /**
             * @description City name filter (case-insensitive)
             * @example Минск
             */
            city?: string;
            /**
             * Format: int64
             * @description City ID filter (from cities reference table)
             * @example 1
             */
            cityId?: number;
            /**
             * @description Minimum price (inclusive)
             * @example 500
             */
            priceMin?: number;
            /**
             * @description Maximum price (inclusive)
             * @example 1500
             */
            priceMax?: number;
            /**
             * Format: int32
             * @description Number of rooms filter
             * @example 2
             */
            rooms?: number;
            /**
             * @description Full-text search query against title, description and address
             * @example двухкомнатная квартира Минск
             */
            query?: string;
            /**
             * @description When true, only listings from direct owners match
             * @example true
             */
            ownerOnly?: boolean;
        };
        /** @description Update a subscription request */
        UpdateSubscriptionRequest: {
            /**
             * @description Subscription display name
             * @example 2-комнатные в центре
             */
            name: string;
            searchCriteria: components["schemas"]["SubscriptionSearchCriteria"];
            /** @description Listing events that trigger a notification */
            triggers: ("NEW_LISTING" | "PRICE_DROP" | "REPOSTED" | "REACTIVATED")[];
            /**
             * @description How often matching listings are delivered
             * @example REALTIME
             * @enum {string}
             */
            deliveryMode: "REALTIME" | "DIGEST" | "DAILY";
            /**
             * @description Delivery channel
             * @example TELEGRAM
             * @enum {string}
             */
            channelType: "TELEGRAM";
            /**
             * @description Minimum price drop percentage for the PRICE_DROP trigger; defaults to 5% when omitted
             * @example 5
             */
            priceDropThreshold?: number;
            quietHoursStart?: components["schemas"]["LocalTime"];
            quietHoursEnd?: components["schemas"]["LocalTime"];
        };
        /** @description Subscription details */
        SubscriptionResponse: {
            /**
             * Format: int64
             * @description Subscription ID
             * @example 42
             */
            id?: number;
            /**
             * @description Subscription display name
             * @example 2-комнатные в центре
             */
            name?: string;
            /**
             * @description Whether the subscription is currently active
             * @example true
             */
            active?: boolean;
            searchCriteria?: components["schemas"]["SubscriptionSearchCriteria"];
            /** @description Listing events that trigger a notification */
            triggers?: ("NEW_LISTING" | "PRICE_DROP" | "REPOSTED" | "REACTIVATED")[];
            /**
             * @description How often matching listings are delivered
             * @example REALTIME
             * @enum {string}
             */
            deliveryMode?: "REALTIME" | "DIGEST" | "DAILY";
            /**
             * @description Delivery channel
             * @example TELEGRAM
             * @enum {string}
             */
            channelType?: "TELEGRAM";
            /**
             * @description Minimum price drop percentage for the PRICE_DROP trigger
             * @example 5
             */
            priceDropThreshold?: number;
            quietHoursStart?: components["schemas"]["LocalTime"];
            quietHoursEnd?: components["schemas"]["LocalTime"];
            /**
             * Format: date-time
             * @description Creation timestamp
             * @example 2026-01-15T11:00:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             * @example 2026-01-15T11:00:00Z
             */
            updatedAt?: string;
        };
        /** @description Create a subscription request */
        CreateSubscriptionRequest: {
            /**
             * @description Subscription display name
             * @example 2-комнатные в центре
             */
            name: string;
            searchCriteria: components["schemas"]["SubscriptionSearchCriteria"];
            /** @description Listing events that trigger a notification */
            triggers: ("NEW_LISTING" | "PRICE_DROP" | "REPOSTED" | "REACTIVATED")[];
            /**
             * @description How often matching listings are delivered
             * @example REALTIME
             * @enum {string}
             */
            deliveryMode: "REALTIME" | "DIGEST" | "DAILY";
            /**
             * @description Delivery channel
             * @example TELEGRAM
             * @enum {string}
             */
            channelType: "TELEGRAM";
            /**
             * @description Minimum price drop percentage for the PRICE_DROP trigger; defaults to 5% when omitted
             * @example 5
             */
            priceDropThreshold?: number;
            quietHoursStart?: components["schemas"]["LocalTime"];
            quietHoursEnd?: components["schemas"]["LocalTime"];
        };
        /** @description Telegram WebApp authentication request */
        TelegramAuthRequest: {
            /**
             * @description Raw initData string provided by the Telegram WebApp via window.Telegram.WebApp.initData
             * @example query_id=AAH...&user=%7B%22id%22%3A123%7D&auth_date=1700000000&hash=abc123
             */
            initData: string;
        };
        /** @description Issued JWT access token */
        AuthResponse: {
            /**
             * @description Signed JWT access token
             * @example eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.abc123
             */
            accessToken?: string;
            /**
             * Format: int64
             * @description Token validity period in seconds
             * @example 3600
             */
            expiresIn?: number;
        };
        /** @description Partial update for a source's enabled state and/or sync interval; omitted fields are left unchanged */
        AdminSourceUpdateRequest: {
            /**
             * @description When false, schedulers skip this source
             * @example false
             */
            enabled?: boolean;
            /**
             * Format: int32
             * @description New interval between scheduled syncs, in minutes
             * @example 90
             */
            syncIntervalMinutes?: number;
        };
        /** @description Data source status and configuration for the admin sources list */
        AdminSourceResponse: {
            /**
             * @description Unique source code, matches ListingConnector#getSourceId()
             * @example onliner
             */
            sourceId?: string;
            /**
             * @description Human-readable source name
             * @example Onliner
             */
            displayName?: string;
            /**
             * @description Base URL of the source platform
             * @example https://r.onliner.by
             */
            url?: string;
            /**
             * @description ISO country code the source serves
             * @example BY
             */
            countryCode?: string;
            /**
             * @description Whether the source's schedulers are allowed to run
             * @example true
             */
            enabled?: boolean;
            /**
             * Format: int32
             * @description Configured interval between scheduled syncs, in minutes
             * @example 60
             */
            syncIntervalMinutes?: number;
            /**
             * Format: date-time
             * @description Finish time of the most recent successful sync, null if never synced
             * @example 2026-08-14T09:00:00Z
             */
            lastSyncAt?: string;
            /**
             * Format: date-time
             * @description When the source was registered
             * @example 2026-01-10T12:00:00Z
             */
            createdAt?: string;
        };
        /** @description Admin request to change a listing's status */
        AdminListingUpdateRequest: {
            /**
             * @description New listing status
             * @example INACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "REPOSTED";
        };
        /** @description Summary view of a real estate listing for list displays */
        ListingSummaryResponse: {
            /**
             * Format: int64
             * @description Internal listing identifier
             * @example 42
             */
            id?: number;
            /**
             * @description Listing title
             * @example 2-комнатная квартира, 52 м², Минск
             */
            title?: string;
            /**
             * @description Listed price in the stored currency
             * @example 75000
             */
            price?: number;
            /**
             * @description Currency code of the stored price
             * @example BYN
             */
            currency?: string;
            /**
             * @description Original price in USD when source publishes in USD; null otherwise
             * @example 85000
             */
            priceUsd?: number;
            /**
             * @description BYN equivalent of the price for USD-priced listings (e.g. Realt.by); null for BYN-priced sources
             * @example 2132
             */
            priceByn?: number;
            /**
             * Format: int32
             * @description Number of rooms
             * @example 2
             */
            rooms?: number;
            /**
             * @description Property type code
             * @example APARTMENT
             */
            propertyType?: string;
            /**
             * @description Total area in square meters
             * @example 52.3
             */
            areaTotalM2?: number;
            /**
             * @description City name
             * @example Минск
             */
            city?: string;
            /**
             * @description District or neighbourhood
             * @example Советский район
             */
            district?: string;
            /**
             * @description Street address
             * @example ул. Пушкина, 5
             */
            address?: string;
            /**
             * @description Source platform code
             * @example realt
             */
            sourceId?: string;
            /**
             * Format: date-time
             * @description Date and time when the listing was published on the source
             * @example 2026-01-15T10:30:00Z
             */
            publishedAt?: string;
            /**
             * @description URL of the main listing photo, null if not available
             * @example https://cdn.realt.by/photos/123456/main.jpg
             */
            photoUrl?: string;
            /**
             * @description URL of the listing on the source platform, used for the open-listing button
             * @example https://re.kufar.by/vi/minsk/snyat-kvartiru/123456
             */
            sourceUrl?: string;
            /**
             * @description True when the seller did not specify a price; display as 'Договорная'
             * @example false
             */
            isNegotiable?: boolean;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageSubscriptionResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["SubscriptionResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"][];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"][];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            direction?: string;
            nullHandling?: string;
            ascending?: boolean;
            property?: string;
            ignoreCase?: boolean;
        };
        /** @description Filter parameters for listing search */
        ListingSearchCriteria: {
            /**
             * @description Deal type filter: RENT, SELL, or RENT_DAILY
             * @example RENT_DAILY
             * @enum {string}
             */
            dealType?: "RENT" | "SELL" | "RENT_DAILY";
            /**
             * @description Property type filter
             * @example APARTMENT
             */
            propertyType?: string;
            /**
             * @description Source platform code filter
             * @example onliner
             */
            sourceId?: string;
            /**
             * @description City name filter (case-insensitive)
             * @example Минск
             */
            city?: string;
            /**
             * Format: int64
             * @description City ID filter (from cities reference table)
             * @example 1
             */
            cityId?: number;
            /**
             * @description Minimum price (inclusive)
             * @example 500
             */
            priceMin?: number;
            /**
             * @description Maximum price (inclusive)
             * @example 1500
             */
            priceMax?: number;
            /**
             * Format: int32
             * @description Number of rooms filter
             * @example 2
             */
            rooms?: number;
            /**
             * @description Listing status filter; defaults to ACTIVE when null
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE" | "REPOSTED";
            /**
             * @description Full-text search query against title, description and address. Supports quoted phrases (\"двухкомнатная квартира\") and minus-word exclusion (-гараж).
             * @example двухкомнатная квартира Минск
             */
            query?: string;
            /**
             * @description When true, only listings from direct owners are returned. Listings from sources that do not provide seller type are always included.
             * @example true
             */
            ownerOnly?: boolean;
        };
        PageListingSummaryResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ListingSummaryResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"][];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        /** @description Full details of a real estate listing */
        ListingResponse: {
            /**
             * Format: int64
             * @description Internal listing identifier
             * @example 42
             */
            id?: number;
            /**
             * @description External identifier from the source platform
             * @example realt-123456
             */
            externalId?: string;
            /**
             * @description Source platform code
             * @example realt
             */
            sourceId?: string;
            /**
             * @description Listing title
             * @example 2-комнатная квартира, 52 м², Минск
             */
            title?: string;
            /**
             * @description Full description provided by the source
             * @example Сдаётся квартира с мебелью
             */
            description?: string;
            /**
             * @description Deal type: RENT, SELL, or RENT_DAILY
             * @example SELL
             * @enum {string}
             */
            dealType?: "RENT" | "SELL" | "RENT_DAILY";
            /**
             * @description Price unit for rental listings: PER_MONTH or PER_DAY. Null for sales.
             * @example PER_MONTH
             * @enum {string|null}
             */
            priceUnit?: "PER_MONTH" | "PER_DAY" | null;
            /**
             * @description Property type
             * @example APARTMENT
             */
            propertyType?: string;
            /**
             * @description Listed price; null when isNegotiable is true
             * @example 75000
             */
            price?: number | null;
            /**
             * @description Human-readable price label; 'Договорная' when no price is set, null otherwise
             * @example Договорная
             */
            priceLabel?: string | null;
            /**
             * @description Currency code
             * @example USD
             */
            currency?: string;
            /**
             * Format: int32
             * @description Number of rooms
             * @example 2
             */
            rooms?: number;
            /**
             * Format: int32
             * @description Floor number
             * @example 5
             */
            floorNumber?: number;
            /**
             * Format: int32
             * @description Total floors in the building
             * @example 9
             */
            floorsTotal?: number;
            /**
             * @description Total area in square meters
             * @example 52.3
             */
            areaTotalM2?: number;
            /**
             * @description Street address
             * @example ул. Якуба Коласа, 5
             */
            address?: string;
            /**
             * @description City name
             * @example Минск
             */
            city?: string;
            /**
             * @description District or neighbourhood
             * @example Советский район
             */
            district?: string;
            /**
             * @description Latitude coordinate
             * @example 53.9006
             */
            latitude?: number;
            /**
             * @description Longitude coordinate
             * @example 27.559
             */
            longitude?: number;
            /**
             * @description True if posted directly by the property owner (not an agency)
             * @example true
             */
            isOwner?: boolean;
            /**
             * @description True when the seller did not specify a price; see priceLabel for display value
             * @example false
             */
            isNegotiable?: boolean;
            /**
             * @description Listing visibility status
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE" | "REPOSTED";
            /**
             * @description URL of the listing on the source platform
             * @example https://realt.by/sale/object/123456/
             */
            sourceUrl?: string;
            /**
             * Format: date-time
             * @description Date and time when the listing was published on the source
             * @example 2026-01-15T10:30:00Z
             */
            publishedAt?: string;
            /**
             * Format: date-time
             * @description Date and time when the listing was first ingested
             * @example 2026-01-15T11:00:00Z
             */
            createdAt?: string;
            /** @description Price change history, newest entry first */
            priceHistory?: components["schemas"]["PriceHistoryEntry"][];
            /**
             * @description True if at least one other listing shares this listing's deduplication hash
             * @example false
             */
            hasDuplicates?: boolean;
        };
        /** @description A single price history record for a listing */
        PriceHistoryEntry: {
            /**
             * @description Price at the recorded time
             * @example 75000
             */
            price?: number;
            /**
             * @description Currency code at the recorded time
             * @example USD
             */
            currency?: string;
            /**
             * Format: date-time
             * @description When this price was recorded
             * @example 2026-01-15T11:00:00Z
             */
            recordedAt?: string;
        };
        /** @description A single recorded connector sync run */
        AdminSyncRunResponse: {
            /**
             * Format: int64
             * @description Internal sync run identifier
             * @example 1024
             */
            id?: number;
            /**
             * @description Source code this run belongs to
             * @example onliner
             */
            sourceId?: string;
            /**
             * @description FULL crawl or incremental DELTA sync
             * @example DELTA
             * @enum {string}
             */
            syncType?: "FULL" | "DELTA";
            /**
             * @description Terminal outcome of the run
             * @example SUCCESS
             * @enum {string}
             */
            status?: "SUCCESS" | "FAILURE";
            /**
             * Format: date-time
             * @description When the run began
             * @example 2026-08-14T14:20:00Z
             */
            startedAt?: string;
            /**
             * Format: date-time
             * @description When the run finished
             * @example 2026-08-14T14:20:42Z
             */
            finishedAt?: string;
            /**
             * Format: int64
             * @description Run duration in milliseconds
             * @example 42000
             */
            durationMs?: number;
            /**
             * Format: int32
             * @description Total listings received from the source
             * @example 340
             */
            listingsFetched?: number;
            /**
             * Format: int32
             * @description New listings persisted
             * @example 12
             */
            listingsAdded?: number;
            /**
             * Format: int32
             * @description Existing listings refreshed
             * @example 28
             */
            listingsUpdated?: number;
            /**
             * Format: int32
             * @description Listings that failed to ingest
             * @example 0
             */
            listingsErrors?: number;
        };
        PageAdminSyncRunResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminSyncRunResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"][];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        /** @description Filter parameters for the admin listing search */
        AdminListingSearchCriteria: {
            /**
             * @description Deal type filter: RENT, SELL, or RENT_DAILY
             * @example RENT_DAILY
             * @enum {string}
             */
            dealType?: "RENT" | "SELL" | "RENT_DAILY";
            /**
             * @description Property type filter
             * @example APARTMENT
             */
            propertyType?: string;
            /**
             * @description Source platform code filter
             * @example onliner
             */
            sourceId?: string;
            /**
             * @description City name filter (case-insensitive)
             * @example Минск
             */
            city?: string;
            /**
             * @description Minimum price (inclusive)
             * @example 500
             */
            priceMin?: number;
            /**
             * @description Maximum price (inclusive)
             * @example 1500
             */
            priceMax?: number;
            /**
             * Format: int32
             * @description Number of rooms filter
             * @example 2
             */
            rooms?: number;
            /**
             * @description Minimum total area in square meters (inclusive)
             * @example 30
             */
            areaMin?: number;
            /**
             * @description Maximum total area in square meters (inclusive)
             * @example 80
             */
            areaMax?: number;
            /**
             * @description Case-insensitive substring match against title, description and address. Unlike the public search's full-text query, this is a plain substring match — moderation tooling favours predictable matches over ranked relevance.
             * @example Минск
             */
            query?: string;
            /**
             * @description Listing status filter; omit to search across all statuses
             * @example INACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE" | "REPOSTED";
            /**
             * @description When true, only returns listings that share their deduplication hash with another listing from a different source — i.e. listings that are part of a duplicate group
             * @example true
             */
            duplicatesOnly?: boolean;
        };
        /** @description User summary for the admin users list */
        AdminUserResponse: {
            /**
             * Format: int64
             * @description Internal user identifier
             * @example 42
             */
            id?: number;
            /**
             * @description User's display name
             * @example Иван Петров
             */
            displayName?: string;
            /**
             * @description User's email, null if not provided
             * @example ivan@example.com
             */
            email?: string;
            /**
             * @description Assigned role
             * @example USER
             * @enum {string}
             */
            role?: "USER" | "PRO" | "ADMIN";
            /**
             * @description Whether the account is active
             * @example true
             */
            active?: boolean;
            /**
             * Format: date-time
             * @description When the account was created
             * @example 2026-01-10T12:00:00Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last time the user was seen, null if never recorded
             * @example 2026-08-14T09:00:00Z
             */
            lastSeen?: string;
        };
        /** @description Partial update for a user's active state and/or role; omitted fields are left unchanged */
        AdminUserUpdateRequest: {
            /**
             * @description When false, deactivates the user
             * @example false
             */
            active?: boolean;
            /**
             * @description New role to assign
             * @example PRO
             * @enum {string}
             */
            role?: "USER" | "PRO" | "ADMIN";
        };
        PageAdminUserResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminUserResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"][];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        /** @description Filter parameters for the admin user search */
        AdminUserSearchCriteria: {
            /**
             * @description Role filter
             * @example ADMIN
             * @enum {string}
             */
            role?: "USER" | "PRO" | "ADMIN";
            /**
             * @description Active status filter
             * @example true
             */
            active?: boolean;
        };
        /** @description A single recorded admin action for the audit log feed */
        AdminAuditLogResponse: {
            /**
             * Format: int64
             * @description Internal audit log entry identifier
             * @example 512
             */
            id?: number;
            /**
             * Format: int64
             * @description Id of the admin who performed the action
             * @example 1
             */
            adminId?: number;
            /**
             * @description Display name of the admin who performed the action, null if the user no longer exists
             * @example Иван Петров
             */
            adminDisplayName?: string;
            /**
             * @description Action performed, matches the action= tag in the SLF4J admin audit log line
             * @example updateListingStatus
             */
            action?: string;
            /**
             * @description Type of resource the action was performed on
             * @example LISTING
             * @enum {string}
             */
            objectType?: "LISTING" | "SOURCE" | "USER";
            /**
             * @description Id of the affected resource — numeric for listings/users, the source code for sources
             * @example 42
             */
            objectId?: string;
            /**
             * Format: date-time
             * @description When the action was performed
             * @example 2026-08-18T14:20:00Z
             */
            createdAt?: string;
        };
        PageAdminAuditLogResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AdminAuditLogResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"][];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    findMine: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriptions page returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageSubscriptionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Active subscription limit exceeded */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    telegramLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramAuthRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description initData signature invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Active subscription limit exceeded */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    pause: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSourceUpdateRequest"];
            };
        };
        responses: {
            /** @description Source updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSourceResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller does not have the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSourceResponse"];
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminListingUpdateRequest"];
            };
        };
        responses: {
            /** @description Listing status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ListingSummaryResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller does not have the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ListingSummaryResponse"];
                };
            };
            /** @description Listing not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                criteria: components["schemas"]["ListingSearchCriteria"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listings page returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageListingSummaryResponse"];
                };
            };
            /** @description Invalid filter parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    findById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listing found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ListingResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Listing not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    findSyncRuns: {
        parameters: {
            query: {
                /** @description Source code filter, e.g. onliner */
                sourceId?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync runs page returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminSyncRunResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller does not have the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAdminSyncRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    findLatestSyncRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest sync runs returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSyncRunResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller does not have the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSyncRunResponse"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    findSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sources returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSourceResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller does not have the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSourceResponse"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query: {
                criteria: components["schemas"]["AdminListingSearchCriteria"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listings page returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageListingSummaryResponse"];
                };
            };
            /** @description Invalid filter parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller does not have the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageListingSummaryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unlinkDuplicateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listing unlinked from its duplicate group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller does not have the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Listing not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
