CREATE TABLE listings
(
  id               BIGSERIAL    PRIMARY KEY,
  external_id      VARCHAR(255) NOT NULL,
  source_id        BIGINT       NOT NULL REFERENCES source (id),
  title            VARCHAR(500) NOT NULL,
  description      TEXT,
  deal_type        VARCHAR(10)  NOT NULL,
  property_type    VARCHAR(50),
  price            NUMERIC(15, 2) NOT NULL,
  currency_id      BIGINT       NOT NULL REFERENCES currency (id),
  price_usd        NUMERIC(15, 2),
  rooms            INTEGER,
  floor_number     INTEGER,
  floors_total     INTEGER,
  area_total_m2    NUMERIC(8, 2),
  area_living_m2   NUMERIC(8, 2),
  area_kitchen_m2  NUMERIC(8, 2),
  address          VARCHAR(500),
  latitude         NUMERIC(10, 7),
  longitude        NUMERIC(10, 7),
  country_id       BIGINT       NOT NULL REFERENCES country (id),
  city             VARCHAR(100),
  district         VARCHAR(100),
  status           VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
  source_url       VARCHAR(1000) NOT NULL,
  published_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_listing_external_source UNIQUE (external_id, source_id)
);
